// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBADfMZVk0iGFl9XEyoTWPOA--dGGu13t4',
    appId: '1:207003889011:android:c06e7ac6fc5501f5bba906',
    messagingSenderId: '207003889011',
    projectId: 'myeduappse',
    storageBucket: 'myeduappse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCua6tFvZ9D8YqBRYUecM47WnQ_7-ccnsA',
    appId: '1:207003889011:ios:7ec925e3a4202ff0bba906',
    messagingSenderId: '207003889011',
    projectId: 'myeduappse',
    storageBucket: 'myeduappse.appspot.com',
    androidClientId: '207003889011-imnl17kum2j9qf2hug7j7c1ptqd8ii1b.apps.googleusercontent.com',
    iosClientId: '207003889011-ftlq0naqte5hrq7jrena4t167f45vj2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.myEduApp',
  );
}
